version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql
    environment:
      PG_PASSWORD: $PGPASSWORD
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
